# Generated by Django 4.2 on 2024-11-21 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RoomWithItems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('amount', models.IntegerField()),
                ('room_with_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='RoomWithItems.roomwithitems')),
                ('item_owner', models.CharField(max_length=255)),
            ],
        ),
    ]
