# Generated by Django 5.1.3 on 2024-11-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
        ('RoomWithItems', '0002_alter_roomwithitems_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_owner',
        ),
        migrations.AddField(
            model_name='item',
            name='attribute',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='room_with_items',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='RoomWithItems.roomwithitems'),
        ),
    ]
