# Generated by Django 5.1.3 on 2024-11-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_remove_item_item_owner_item_attribute_item_type_and_more'),
        ('RoomWithItems', '0002_alter_roomwithitems_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='room_with_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='RoomWithItems.roomwithitems'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
