# Generated by Django 5.1.3 on 2024-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0004_item_building_item_end_date_item_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(default='Unknown', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='room_with_items',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
