# Generated by Django 5.1.3 on 2024-11-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0007_remove_item_id_alter_item_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='room_with_items',
        ),
        migrations.AddField(
            model_name='item',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
