version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: python_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOST=db
    entrypoint: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate &&
             python manage.py resetdb &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
