# Generated by Django 4.2 on 2024-11-21 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomToRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('is_to_rent', models.BooleanField(default=True, editable=False, blank=True)),
                ('building',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_to_rent',to='Building.building')),
            ],
            options={
                'unique_together': {('room_number', 'building')},
            },
        ),
    ]
