# Generated by Django 5.1.3 on 2024-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomToRent', '0002_alter_roomtorent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtorent',
            name='faculty',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='roomtorent',
            name='room_to_rent_id',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtorent',
            name='building',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomtorent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
