# Generated by Django 5.1.3 on 2024-11-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomToRent', '0003_roomtorent_faculty_roomtorent_room_to_rent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtorent',
            name='room_to_rent_id',
        ),
        migrations.AlterField(
            model_name='roomtorent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
