# Generated by Django 5.1.3 on 2024-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomWithItems', '0002_alter_roomwithitems_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomwithitems',
            name='building',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
