# Generated by Django 4.2.6 on 2024-11-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembooking',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
