# Generated by Django 5.1.3 on 2024-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemBooking', '0002_alter_itembooking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembooking',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
