# Generated by Django 5.1.3 on 2024-11-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemBooking', '0004_remove_itembooking_item_remove_itembooking_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembooking',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
