# Generated by Django 5.1.3 on 2024-11-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0002_alter_building_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='faculty',
        ),
    ]
