# Generated by Django 5.1.3 on 2024-11-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0003_remove_building_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='faculty',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
