# Generated by Django 5.1.3 on 2024-11-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_remove_faculty_admin_faculty_admin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
