# Generated by Django 5.1.3 on 2024-11-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_to_rent',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='building',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='faculty',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='item_id',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='item_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_id',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
