# Generated by Django 5.1.3 on 2024-11-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_remove_booking_room_to_rent_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isRoomToRent',
            field=models.BooleanField(default=True),
        ),
    ]
