# Generated by Django 5.1.3 on 2024-11-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_remove_booking_id_remove_booking_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
